export default {
  subtraits: [
    {
      id: 'subtrait-distinction-sfx',
      hasConsumableDice: false,
      hasDescription: true,
      hasDice: false,
      hasLabel: true,
      hasMaxNumberField: false,
      hasNumberField: false,
      hasTags: false,
      isRolledSeparately: false,
      isUnlockable: true,
      maxDiceAmount: 1,
      maxDieRating: 12,
      maxNumberFieldLabel: null,
      minDiceAmount: 1,
      minDieRating: 4,
      name: 'Distinction SFX',
      numberFieldLabel: null,
    },
  ],
  traits: [
    {
      id: 'trait-distinction',
      hasConsumableDice: false,
      hasDescription: true,
      hasDice: false,
      hasLabel: true,
      hasMaxNumberField: false,
      hasNumberField: false,
      hasTags: false,
      isRolledSeparately: false,
      isUnlockable: false,
      maxDiceAmount: 1,
      maxDieRating: 8,
      maxNumberFieldLabel: null,
      minDiceAmount: 1,
      minDieRating: 8,
      name: 'Distinction',
      numberFieldLabel: null,
      subtraitTypes: [
        'subtrait-distinction-sfx',
      ],
    },
  ],
}